divert(`-1')
changequote(`«', `»')
changecom

The common header. Each line is prefixed with "# " by default; the
caller may change this by specifying an argument.

define(«__header__», «dnl
ifelse(«$#», «0», «# », «$1»)dnl
Generated by dotfiles setup: esyscmd(«printf %s "$(date)"»)
ifelse(«$#», «0», «# », «$1»)-----dnl
»)

TODO: Write a macro to quote special shell characters.

divert«»dnl
