# Defaults.

prefix := $(wildcard ~)
colemakerel := .colemakerel


# Template substitution helpers.

nullstring :=
space := $(nullstring) #EOL

encode = $(subst $(space),SPACE,$(1))
decode = $(subst SPACE, ,$(1))


# Shared template parameters.

HEADER := "\#\#\# Generated by Colemakerel setup: $$(date) \#\#\#\n\n"

SUBSTITUTIONS := $(call encode,s|__PREFIX__|$(prefix)|g)
SUBSTITUTIONS += $(call encode,s|__COLEMAKEREL__|$(colemakerel)|g)


# Treat each child directory as a "module" and create lists of output
# files based on each module's subdirectory layout.
# - tmux_FILES: list of output files to be generated by the "tmux" module
# - vim_FILES: list of output files to be generated by the "vim" module
# ... etc.

MODULES := $(patsubst %/,%,$(wildcard */))

define create_module_FILES
FILES := $$(shell find $(1) -type f ! \( -name module.mk -o \
                                         -name '*.sw?' -o \
                                         -name '*~' \)\
    )
FILES := $$(patsubst $(1)/%,%,$$(FILES))
FILES := $$(patsubst _%,.%,$$(FILES))

$(1)_FILES := $$(addprefix $$(prefix)/,$$(FILES))
endef

$(foreach module,$(MODULES),$(eval $(call create_module_FILES,$(module))))


# Module-specific settings.

include $(addsuffix /module.mk,$(MODULES))


# The default rule does substitutions on the source templates and writes
# them to the output files.

VPATH := $(MODULES)

SED_SCRIPTS := $(foreach sub,$(SUBSTITUTIONS),-e '$(call decode,$(sub))')

.DELETE_ON_ERROR:
# mkdir -p may cause race conditions
.NOTPARALLEL:
.SECONDEXPANSION:

REPLACELEADINGDOTWITHUNDERSCORE = $(patsubst .%,_%,$*)
$(prefix)/% : $$(REPLACELEADINGDOTWITHUNDERSCORE)
	@mkdir -p -- "$(dir $@)"
	@printf $(HEADER) > "$@"
	@sed -E $(SED_SCRIPTS) "$<" >> "$@"
	@printf "Wrote $@\n" >&2


# Install and uninstall all modules.

ALL_FILES := $(foreach module,$(MODULES),$($(module)_FILES))

.DEFAULT_GOAL := install
.PHONY: install
install: $(ALL_FILES)

.PHONY: uninstall
uninstall:
	-rm -R $(ALL_FILES)


# Create module-specific install/uninstall targets.

define create_module_targets
.PHONY: $(1) $(1)-install $(1)-uninstall
$(1) $(1)-install: $$($(1)_FILES)
$(1)-uninstall:
	-rm -R $$($(1)_FILES)
endef

$(foreach module,$(MODULES),$(eval $(call create_module_targets,$(module))))


# Flotsam and jetsam

SHELL := /bin/sh

.SUFFIXES:
